
# Default values for prometheus-rabbitmq-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: kbudde/rabbitmq-exporter
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  externalPort: 9419
  internalPort: 9419
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

priorityClassName: ""

nodeSelector:
  kubernetes.io/hostname: minikube-m02

tolerations: []

affinity: {}

loglevel: debug
rabbitmq:
  url: http://10.106.138.43:15672
  user: user
  password: WGpsHxZFLu
  # If existingPasswordSecret is set then password is ignored
  existingPasswordSecret: ~
  existingPasswordSecretKey: password
  capabilities: bert,no_sort
  include_queues: ".*"
  include_vhost: ".*"
  skip_queues: "^$"
  skip_verify: "false"
  skip_vhost: "^$"
  exporters: "connections,shovel,federation,exchange,node,queue,memory"
  output_format: "TTY"
  timeout: 30
  max_queues: 0

podLabels: {}

annotations: {}
#  prometheus.io/scrape: "true"
#  prometheus.io/path: "/metrics"
#  prometheus.io/port: 9419

prometheus:
  monitor:
    enabled: true
    additionalLabels:
      release: prometheus
    interval: 1s
    namespace: []
  rules:
    enabled: false
    additionalLabels: {}
