
## Using default values from https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
##
grafana:
  enabled: true
  nodeSelector: 
    kubernetes.io/hostname: minikube

## Component scraping the kube api server
##
kubeApiServer:
  enabled: true

## Component scraping the kubelet and kubelet-hosted cAdvisor
##
kubelet:
  enabled: true

## Component scraping the kube controller manager
##
#kubeControllerManager:
#  enabled: true
#
#coreDns:
#  enabled: true
### Component scraping kubeDns. Use either this or coreDns
###
#kubeDns:
#  enabled: true
#
### Component scraping etcd
###
#kubeEtcd:
#  enabled: true
#
### Component scraping kube scheduler
###
#kubeScheduler:
#  enabled: true
#
### Component scraping kube proxy
###
#kubeProxy:
#  enabled: true

## Component scraping kube state metrics
##

## Configuration for kube-state-metrics subchart
##
kube-state-metrics:
  nodeSelector:
    kubernetes.io/hostname: minikube


## Deploy node exporter as a daemonset to all nodes
##
nodeExporter:
  enabled: true

## Configuration for prometheus-node-exporter subchart
##
prometheus-node-exporter:
  namespaceOverride: ""
  nodeSelector:
    kubernetes.io/hostname: minikube-m02
  podLabels:
    ## Add the 'node-exporter' label to be used by serviceMonitor to match standard common usage in rules and grafana dashboards
    ##
    jobLabel: node-exporter
  extraArgs:
    - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/.+)($|/)
    - --collector.filesystem.ignored-fs-types=^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$
  service:
    portName: http-metrics
  prometheus:
    monitor:
      enabled: true
      jobLabel: jobLabel

      ## Scrape interval. If not set, the Prometheus default scrape interval is used.
      ##
      interval: "1s"

      ## How long until a scrape request times out. If not set, the Prometheus default scape timeout is used.
      ##
      scrapeTimeout: "1s"


## Configuration for alertmanager
## ref: https://prometheus.io/docs/alerting/alertmanager/
##
alertmanager:

  ## Deploy alertmanager
  ##
  enabled: false
  nodeSelector:
    kubernetes.io/hostname: minikube

## Manages Prometheus and Alertmanager components
##
prometheusOperator:
  enabled: true
  nodeSelector: 
    kubernetes.io/hostname: minikube
  kubeletService:
    enabled: true
      ## Create a servicemonitor for the operator
  ##
  serviceMonitor:
    ## Scrape interval. If not set, the Prometheus default scrape interval is used.
    ##
    interval: ""
    ## Scrape timeout. If not set, the Prometheus default scrape timeout is used.
    scrapeTimeout: ""
    selfMonitor: true
## Deploy a Prometheus instance
##
prometheus:

  enabled: true
  serviceMonitor:
    enabled: true
    ## Scrape interval. If not set, the Prometheus default scrape interval is used.
    ##
    interval: ""
  prometheusSpec:
    nodeSelector: 
      kubernetes.io/hostname: minikube