
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-deployment
  labels:
    app: workload-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-simulator
  template:
    metadata:
      labels:
        app: workload-simulator
    spec:
      nodeSelector:
        kubernetes.io/hostname: minikube-m02
      containers:
      - name: workload-simulator
        image: babaksit/workload_simulator:v0.0.3
        env:
          - name: RABBITMQ_HOST
            value: 
        args: ["--cpu-scale", "{{ .Values.cpuScale }}",
               "--memory-scale", "{{ .Values.memoryScale }}", 
               "--rabbitmq-host", "{{ .Values.rabbitmqHost }}",
               "--file-path", {{ .Values.dirPath }}{{ .Values.filePath }}]
        volumeMounts:
          - mountPath: {{ .Values.dirPath }}
            name: mydir
          - mountPath: {{ .Values.dirPath }}{{ .Values.filePath }}
            name: myfile
      volumes:
        - name: mydir
          hostPath:
            path: {{ .Values.dirPath }}
            type: DirectoryOrCreate
        - name: myfile
          hostPath:
            path: {{ .Values.dirPath }}{{ .Values.filePath }}
            type: FileOrCreate

